export const brand = {
  name: "Li&Media",
  shortName: "Media",
  slogan: "把照片和视频整理成可以回看的记忆",
  description: "基于百度网盘存储的公开回忆库。",
  themeStorageKey: "limedia-theme",
  copy: {
    libraryTitle: "回忆库",
    libraryDescription: "按拍摄时间浏览照片与视频回忆。",
    allKinds: "全部",
    photoKind: "照片",
    videoKind: "视频",
    searchLabel: "搜索回忆",
    searchPlaceholder: "搜索标题、描述或地点",
    clearSearch: "清除搜索",
    loadingLibrary: "正在加载回忆",
    loadFailed: "暂时无法加载回忆库",
    loadFailedAction: "重新加载",
    emptyLibrary: "还没有公开的回忆内容。",
    emptySearch: "没有匹配的回忆。",
    firstPage: "已是第一页",
    previousPage: "上一页",
    nextPage: "下一页",
    lastPage: "已是最后一页",
    breadcrumbHome: "首页",
    breadcrumbLibrary: "回忆库",
    breadcrumbDetail: "详情",
    detailMediaLoading: "媒体加载中",
    detailOpenViewer: "打开图片查看器",
    detailImageLoadFailed: "图片加载失败",
    detailPlaybackFailed: "视频播放失败",
    detailRetry: "重试",
    detailDescription: "回忆说明",
    detailCapture: "拍摄信息",
    detailCaptureTime: "拍摄时间",
    detailLocation: "地点",
    detailFile: "文件信息",
    detailFileSource: "来源",
    detailFileFormat: "格式",
    detailFileSize: "大小",
    detailFileStatus: "状态",
    detailDimensions: "尺寸",
    detailDuration: "时长",
    notFoundTitle: "页面不存在",
    notFoundText: "请检查地址，或回到回忆库首页。",
    backHome: "返回首页",
    backTop: "返回顶部",
    moreMenu: "更多",
    navLabel: "主导航",
    paginationLabel: "分页",
    breadcrumbLabel: "面包屑",
    themeLabel: "切换主题",
    themeLight: "切换到浅色主题",
    themeDark: "切换到深色主题",
    adminEntry: "管理",
    adminTitle: "回忆管理",
    adminDescription: "上传照片或视频，确认后即可在公开页面展示。",
    adminLoginTitle: "管理登录",
    adminLoginDescription: "请输入管理令牌以继续操作。",
    adminTokenLabel: "管理令牌",
    adminLogin: "进入管理",
    adminLoginFailed: "管理令牌不正确，或服务暂时不可用",
    adminLogout: "退出登录",
    adminAllMemories: "全部回忆",
    adminTitleLabel: "标题（可留空，自动读取文件名或元数据）",
    adminDescriptionLabel: "描述",
    adminLocationLabel: "地点",
    adminCapturedAtLabel: "拍摄时间",
    adminFileLabel: "文件",
    adminUpload: "上传并发布",
    adminUploading: "上传中",
    adminSync: "同步网盘",
    adminSyncing: "同步中",
    adminSyncSuccess: "网盘同步完成。",
    adminSyncFailed: "网盘同步失败",
    adminSyncStatusHeader: "同步状态",
    adminLastSyncedHeader: "最近同步",
    adminNeverSynced: "未同步",
    adminSelectMemory: "选择回忆",
    adminSelectAll: "选择全部回忆",
    adminBatchEdit: "批量修改",
    adminBatchPublish: "批量发布",
    adminBatchHide: "批量下架",
    adminExportReport: "导出报告",
    adminBatchEditTitle: "批量修改回忆",
    adminBatchSave: "保存修改",
    adminSelectedCount: "已选择",
    adminBatchUpdateFailed: "批量操作失败",
    adminExportFailed: "报告导出失败",
    adminUploadQueue: "上传队列",
    adminUploadPending: "待上传",
    adminUploadUploading: "上传中",
    adminUploadSuccessItem: "上传成功",
    adminUploadFailedItem: "上传失败",
    adminRetryUpload: "重试上传",
    adminSelectFile: "请选择要上传的照片或视频文件",
    adminUploadSuccess: "上传成功，公开列表已即时展示。",
    adminUploadFailed: "上传失败，请稍后重试",
    adminFileHeader: "回忆",
    adminKindHeader: "类型",
    adminStatusHeader: "状态",
    adminFileStatusHeader: "文件",
    adminActionsHeader: "操作",
    adminPublish: "发布",
    adminHide: "下架",
    adminDelete: "删除",
    adminDeleteConfirmTitle: "确认删除这条回忆？",
    adminDeleteConfirmText: "删除后对应文件会一起移除，无法恢复。",
    adminCancel: "取消",
    adminConfirmDelete: "删除",
    adminStatusUpdateFailed: "状态更新失败",
    adminDeleteFailed: "删除失败",
    adminLoading: "正在加载管理列表",
    adminEmpty: "还没有上传内容。",
    statusPublished: "已发布",
    statusDraft: "草稿",
    statusPending: "待处理",
    statusHidden: "已下架",
    statusError: "错误",
    fileMatched: "已就绪",
    fileDiscovered: "已发现",
    filePending: "待同步",
    fileSyncing: "同步中",
    fileMissing: "缺失",
    fileRemoved: "已移除",
    fileFailed: "失败",
    noDescription: "暂无描述。",
    bytes: "字节",
  },
  nav: [
    { label: "首页", href: "/" },
    { label: "照片", href: "/?kind=photo" },
    { label: "视频", href: "/?kind=video" },
  ],
  footerLinks: [] as ReadonlyArray<{ label: string; href: string }>,
  copyrightHolder: "黎智锋",
  icp: "",
  publicSecurityFiling: "",
  assets: {
    favicon: "/favicon.svg",
    logo: { name: "brand-logo.webp", alt: "Li&Media", viewBox: "1/1" },
    faviconSpec: "透明底 SVG，最小显示 16px，周围净空不少于图标边长的 1/4。",
    logoSpec: "透明底 512x512 WebP，最小显示 32px，周围净空不少于图标边长的 1/4。",
  },
} as const;

export type Brand = typeof brand;
